# tests/test_depscan_noise.py -- issue #75: path-class tags and noise filters
import sys
import tempfile
import unittest
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "dependency-model" / "scripts"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from depscanlib.report import build_scan
from repobuilder import build_repo

K8S = ("apiVersion: v1\nkind: PersistentVolumeClaim\nspec:\n"
       "  resources:\n    requests:\n      storage: 10Gi\n"
       "  storage: true\n  memory: default\n")


class TestNoise(unittest.TestCase):
    def scan(self, files):
        with tempfile.TemporaryDirectory() as tmp:
            return build_scan(build_repo(tmp, files))

    def test_path_class_tags_every_finding(self):
        line = 'x = "http://example.com/a"  # PASSWORD: 1\n'
        scan = self.scan({
            "app/main.py": line,
            "app/main_test.go": line,
            "tests/t.py": line,
            "docs/a.md": line,
            "third_party/lib/x.py": line,
            "api/gen.go": "// Code generated by x DO NOT EDIT.\n" + line,
            "deploy/calico.yml": "# Vendored from: https://x\n" + K8S,
        })
        by_file = {f["file"]: f["path_class"]
                   for f in scan["findings"]["url_literals"]}
        self.assertEqual(by_file, {
            "app/main.py": "first-party", "app/main_test.go": "test",
            "tests/t.py": "test", "docs/a.md": "docs",
            "third_party/lib/x.py": "vendored", "api/gen.go": "generated",
            "deploy/calico.yml": "vendored"})
        for records in scan["findings"].values():
            self.assertTrue(all("path_class" in r for r in records))
        self.assertEqual(scan["file_classes"]["deploy/calico.yml"], "vendored")

    def test_host_port_rejects_non_hosts(self):
        scan = self.scan({"m.go": 'Name string `gorm:"size:256;type:varchar"`\n'
                                  "tcp:179 main.go:16 db:5432 a.example.com:8080\n"})
        hosts = sorted(f["host"] for f in scan["findings"]["host_port_literals"])
        self.assertEqual(hosts, ["a.example.com", "db"])

    def test_resource_limits_ignore_non_quantities(self):
        scan = self.scan({"pvc.yaml": K8S})
        self.assertEqual([r["raw"] for r in scan["findings"]["resource_limits"]],
                         ["10Gi"])


if __name__ == "__main__":
    unittest.main()
