"""Tag a repo path as first-party, test, docs, vendored, or generated.

The scanner never drops a finding by class: it tags, and each skill decides
what to keep. Path rules come first (cheap); the file's leading bytes are
read only to catch what a path cannot show -- a vendored manifest or generated
code that lives at an ordinary path. First match wins, in this order:
vendored, generated, test, docs, first-party.
"""

import re
from pathlib import PurePosixPath

from depscanlib.walk import read_text

VENDORED_DIRS = {"vendor", "vendored", "node_modules", "third_party",
                 "third-party", "thirdparty", "external"}
TEST_DIRS = {"test", "tests", "__tests__", "testdata", "fixtures", "e2e",
             "spec", "specs"}
DOCS_DIRS = {"docs", "doc", "documentation", "wiki"}
DOCS_SUFFIXES = {".md", ".mdx", ".rst", ".adoc"}
TEST_NAME_RE = re.compile(
    r'(_test\.[a-z]+|^test_.*\.py|_test\.py|\.(test|spec)\.[cm]?[jt]sx?|'
    r'^conftest\.py|Tests?\.(java|kt|cs))$')
GENERATED_NAME_RE = re.compile(
    r'(\.pb\.go|_generated\.go|\.gen\.go|^zz_generated.*|\.g\.dart|_pb2\.py|'
    r'\.generated\.[a-z]+)$')

HEAD = 1024
VENDORED_MARK_RE = re.compile(r'\bvendored (?:from|on)\b', re.IGNORECASE)
GENERATED_MARK_RE = re.compile(
    r'code generated|do not edit|autogenerated|auto-generated|controller-gen',
    re.IGNORECASE)


def classify_path(root, path):
    parsed = PurePosixPath(path)
    dirs, name = set(parsed.parts[:-1]), parsed.name
    if dirs & VENDORED_DIRS:
        return "vendored"
    head = read_text(root, path, HEAD)
    if VENDORED_MARK_RE.search(head):
        return "vendored"
    if GENERATED_NAME_RE.search(name) or GENERATED_MARK_RE.search(head):
        return "generated"
    if dirs & TEST_DIRS or TEST_NAME_RE.search(name):
        return "test"
    if dirs & DOCS_DIRS or parsed.suffix.lower() in DOCS_SUFFIXES:
        return "docs"
    return "first-party"


def tag_paths(root, records):
    """Add `path_class` to every record with a `file`, in place."""
    cache = {}
    for rec in records:
        path = rec["file"]
        if path not in cache:
            cache[path] = classify_path(root, path)
        rec["path_class"] = cache[path]
    return records
